<?php

/**
 * @file
 * Amino Page Builder hooks and functions.
 */

use Drupal\amino_page_builder\LayoutPreprocess;

/**
 * Implements hook_preprocess_HOOK().
 */
function amino_page_builder_preprocess_layout(&$variables) {
  \Drupal::service('class_resolver')
    ->getInstanceFromDefinition(LayoutPreprocess::class)
    ->preprocessLayout($variables);
}

/**
 * Implements hook_theme().
 */
function amino_page_builder_theme($existing, $type, $theme, $path) {
  return [
   'paragraph__amino_expandable_content' => [
      'template' => 'paragraphs/paragraph--amino-expandable-content',
      'base hook' => 'paragraph'
    ],
  ];
}
